const express=require('express');
const router=express.Router();
const goodaraivalliController=require('../controllers/goodaraivalli_controller');
router.post('/createDate',goodaraivalliController.createDatePrice);
router.post('/getDate',goodaraivalliController.getDatePrice);
router.post('/getAllPrice',goodaraivalliController.getAllPrice);
router.post('/deleteDate',goodaraivalliController.deleteDate);
router.post('/newBooking',goodaraivalliController.newBooking);
router.post('/myBookings',goodaraivalliController.myBookings);
router.post('/bookings',goodaraivalliController.allBookings);
router.post('/updateBooking',goodaraivalliController.updateStatus);
router.post('/getBookingDetail',goodaraivalliController.getBookingDetail);
router.post('/updatePaymentStatus',goodaraivalliController.updatePaymentStatus);
module.exports=router;
